# =========================================================================
# ASTRO + TAILWIND v4 STATIC SITE — devShell + Nix-built nginx image
# =========================================================================
# Generated by:  nix flake init -t ~/.omni-nix#astro
#
# Defines:
#   1. devShells.default — nodejs + npm + wrangler, direnv-loaded.
#   2. packages.image    — an OCI image: nginx serving the built static site.
#   3. packages.site     — the built site itself (Cloudflare Pages upload).
#
# ⚠️ DEPS HASH (inherent to reproducible JS builds in Nix): buildNpmPackage
# needs `npmDepsHash` matching app/package-lock.json. This template SHIPS the
# real hash (it matches the committed app/package-lock.json), so `just build`
# works out of the box. When you change deps:
#   1. enter the shell:       direnv allow   (or `nix develop`)
#   2. refresh the lockfile:  (cd app && npm install)
#   3. just relock            # recomputes the hash + writes it into npmDepsHash below
#   4. just build
# (Re-run `just relock` whenever deps change — it runs prefetch-npm-deps for you.)
#
# Dev → deploy loop (after the hash is set):
#     just build && just push && just deploy        # k3s (local)
#     just cf                                        # Cloudflare Pages (public)
#
# ASTRO ≠ REACT (why this isn't a copy of #react):
#   • Static output is FILE-PER-ROUTE (dist/about/index.html), not an SPA —
#     nginx falls back to =404, NOT /index.html. If you later switch Astro to
#     `output: 'hybrid'/'server'` with an adapter, that changes (and then a
#     node image, not nginx, is the right runtime).
#   • Tailwind v4 is a Vite plugin (astro.config.mjs) — no tailwind.config.js,
#     no postcss.config.js; theme tokens live in CSS (@theme in global.css).
#   • Telemetry is disabled in the build (ASTRO_TELEMETRY_DISABLED) so the
#     offline sandbox never tries to phone home or write $HOME.
# =========================================================================
{
  description = "Astro + Tailwind site — Nix devShell + nginx image, just → k3s";

  inputs.nixpkgs.url = "nixpkgs/nixos-26.05";

  outputs = { self, nixpkgs }:
    let
      systems = [ "x86_64-linux" ];
      forAllSystems = nixpkgs.lib.genAttrs systems;
      pkgsFor = system: nixpkgs.legacyPackages.${system};

      imageName = "localhost:5000/astro-app";   # keep in lockstep with justfile + manifests
      imageTag  = "latest";
    in {
      packages = forAllSystems (system:
        let
          pkgs = pkgsFor system;
          lib  = nixpkgs.lib;

          # ── build the static site (reproducible, OFFLINE via npmDepsHash) ──
          # buildNpmPackage runs `npm ci` (offline, deps resolved from the
          # hash) then `npm run build` → dist/. installPhase exposes dist/.
          astroBuild = pkgs.buildNpmPackage {
            pname = "astro-app";
            version = "0.1.0";
            src = ./app;
            npmDepsHash = "sha256-CTe1rny0UyujIc6yPUtL1p6gYby6mXc+FXTqKS8ndNA=";  # from app/package-lock.json via just relock
            env.ASTRO_TELEMETRY_DISABLED = "1";    # offline sandbox: never write $HOME / phone home
            installPhase = ''
              runHook preInstall
              mkdir -p $out
              cp -r dist/* $out/
              runHook postInstall
            '';
          };

          # ── nginx config (same writable-path + docroot pattern as #hugo) ──
          # NOT the SPA fallback of #react — Astro's static output is
          # file-per-route; unknown paths 404 (Cloudflare Pages does the same
          # by default for this kind of site).
          nginxConf = pkgs.writeText "nginx.conf" ''
            daemon off;              # foreground (PID 1) — daemon mode forks + the container exits
            worker_processes 1;
            error_log /dev/stderr warn;
            pid        /tmp/nginx.pid;
            events { worker_connections 1024; }
            http {
              access_log /dev/stdout;
              client_body_temp_path /tmp/client_temp;
              proxy_temp_path       /tmp/proxy_temp;
              fastcgi_temp_path     /tmp/fastcgi_temp;
              uwsgi_temp_path       /tmp/uwsgi_temp;
              scgi_temp_path        /tmp/scgi_temp;
              include ${pkgs.nginx}/conf/mime.types;
              default_type application/octet-stream;
              server {
                listen 8080;          # non-root can't bind <1024; 8080 is the safe high port
                root  ${astroBuild};
                index index.html;
                # static file-per-route: real files, real 404s (no SPA rewrite)
                location / { try_files $uri $uri/ =404; }
                # Astro's hashed build output — immutable, cache hard
                location /_astro/ { add_header Cache-Control "public, max-age=31536000, immutable"; }
              }
            }
          '';

          # Non-root user (UID 1000) baked in so the manifest can set
          # runAsNonRoot + runAsUser=1000. nginx runs as this uid.
          nonRootUser = pkgs.runCommand "non-root-user" { } ''
            mkdir -p $out/etc
            printf 'root:x:0:0::/root:/bin/sh\nappuser:x:1000:1000::/nonexistent:/bin/sh\n' > $out/etc/passwd
            printf 'root:x:0:\nappuser:x:1000:\n'                                       > $out/etc/group
          '';
        in {
          default = self.packages.${system}.image;
          site  = astroBuild;          # built static site → `nix build .#site` (Cloudflare Pages upload)
          image = pkgs.dockerTools.buildImage {
            name = imageName;
            tag  = imageTag;
            copyToRoot = [
              pkgs.nginx
              astroBuild
              nonRootUser
            ];
            config = {
              User         = "1000:1000";
              # -e /dev/stderr: pre-config error log to stderr (never /var/log/nginx).
              # /tmp (pid+temp) comes from mounts: emptyDir in k3s, --tmpfs in `just test`.
              Cmd          = [ "${pkgs.nginx}/bin/nginx" "-c" nginxConf "-e" "/dev/stderr" ];
              ExposedPorts = { "8080/tcp" = { }; };
            };
          };
        });

      devShells = forAllSystems (system:
        let pkgs = pkgsFor system; in {
          default = pkgs.mkShell {
            packages = with pkgs; [
              nodejs_22    # includes npm — dev + image both use npm (no pnpm drift)
              just skopeo kubectl
              wrangler     # Cloudflare Pages direct-upload deploy (just cf)
            ];
            shellHook = ''
              echo ""
              echo "  ❯ astro devshell active"
              echo "      node    $(node -v 2>/dev/null || echo '—')"
              echo "      image   ${imageName}:${imageTag}"
              echo "      serve   npm run dev   (→ http://localhost:4321)"
              echo "      deploy  just build && just push && just deploy   (k3s)"
              echo "      cf      just cf                                          (Cloudflare Pages)"
              echo "      deps    (cd app && npm install) → just relock → just build"
              echo ""
            '';
          };
        });
    };
}
